package com.grailslab

/**
 * Created by Aminul on 5/17/2016.
 */
class TopSheetReference {
    String param0Name
    String param1Name
    String param2Name
    String param3Name
    String param4Name
    String param5Name
    String param6Name
    String param7Name
    String param8Name
    String param9Name
    String param10Name
    String param11Name
    String param12Name
    String param13Name
    String param14Name
    String param15Name
    String param16Name
    String param17Name
    String param18Name
    String param19Name

    Integer param0absent
    Integer param1absent
    Integer param2absent
    Integer param3absent
    Integer param4absent
    Integer param5absent
    Integer param6absent
    Integer param7absent
    Integer param8absent
    Integer param9absent
    Integer param10absent
    Integer param11absent
    Integer param12absent
    Integer param13absent
    Integer param14absent
    Integer param15absent
    Integer param16absent
    Integer param17absent
    Integer param18absent
    Integer param19absent

    Integer  param0pass
    Integer  param1pass
    Integer  param2pass
    Integer  param3pass
    Integer  param4pass
    Integer  param5pass
    Integer  param6pass
    Integer  param7pass
    Integer  param8pass
    Integer  param9pass
    Integer  param10pass
    Integer  param11pass
    Integer  param12pass
    Integer  param13pass
    Integer  param14pass
    Integer  param15pass
    Integer  param16pass
    Integer  param17pass
    Integer  param18pass
    Integer  param19pass

    Integer  param0fail
    Integer  param1fail
    Integer  param2fail
    Integer  param3fail
    Integer  param4fail
    Integer  param5fail
    Integer  param6fail
    Integer  param7fail
    Integer  param8fail
    Integer  param9fail
    Integer  param10fail
    Integer  param11fail
    Integer  param12fail
    Integer  param13fail
    Integer  param14fail
    Integer  param15fail
    Integer  param16fail
    Integer  param17fail
    Integer  param18fail
    Integer  param19fail

    Integer  param0aPlus
    Integer  param1aPlus
    Integer  param2aPlus
    Integer  param3aPlus
    Integer  param4aPlus
    Integer  param5aPlus
    Integer  param6aPlus
    Integer  param7aPlus
    Integer  param8aPlus
    Integer  param9aPlus
    Integer  param10aPlus
    Integer  param11aPlus
    Integer  param12aPlus
    Integer  param13aPlus
    Integer  param14aPlus
    Integer  param15aPlus
    Integer  param16aPlus
    Integer  param17aPlus
    Integer  param18aPlus
    Integer  param19aPlus

    Integer  param0a
    Integer  param1a
    Integer  param2a
    Integer  param3a
    Integer  param4a
    Integer  param5a
    Integer  param6a
    Integer  param7a
    Integer  param8a
    Integer  param9a
    Integer  param10a
    Integer  param11a
    Integer  param12a
    Integer  param13a
    Integer  param14a
    Integer  param15a
    Integer  param16a
    Integer  param17a
    Integer  param18a
    Integer  param19a

    Integer  param0aMinus
    Integer  param1aMinus
    Integer  param2aMinus
    Integer  param3aMinus
    Integer  param4aMinus
    Integer  param5aMinus
    Integer  param6aMinus
    Integer  param7aMinus
    Integer  param8aMinus
    Integer  param9aMinus
    Integer  param10aMinus
    Integer  param11aMinus
    Integer  param12aMinus
    Integer  param13aMinus
    Integer  param14aMinus
    Integer  param15aMinus
    Integer  param16aMinus
    Integer  param17aMinus
    Integer  param18aMinus
    Integer  param19aMinus

    Integer  param0b
    Integer  param1b
    Integer  param2b
    Integer  param3b
    Integer  param4b
    Integer  param5b
    Integer  param6b
    Integer  param7b
    Integer  param8b
    Integer  param9b
    Integer  param10b
    Integer  param11b
    Integer  param12b
    Integer  param13b
    Integer  param14b
    Integer  param15b
    Integer  param16b
    Integer  param17b
    Integer  param18b
    Integer  param19b

    Integer  param0c
    Integer  param1c
    Integer  param2c
    Integer  param3c
    Integer  param4c
    Integer  param5c
    Integer  param6c
    Integer  param7c
    Integer  param8c
    Integer  param9c
    Integer  param10c
    Integer  param11c
    Integer  param12c
    Integer  param13c
    Integer  param14c
    Integer  param15c
    Integer  param16c
    Integer  param17c
    Integer  param18c
    Integer  param19c


}
